receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  file:
    path: ./logs.json
    rotation:
  otlp/traces:
    endpoint: data-prepper:21890
    tls:
      insecure: true
      insecure_skip_verify: true
  otlp/metrics:
    endpoint: data-prepper:21891
    tls:
      insecure: true
      insecure_skip_verify: true
  otlp/logs:
    endpoint: data-prepper:21892
    tls:
      insecure: true
      insecure_skip_verify: true

service:
  telemetry:
    logs:
      level: DEBUG
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp/traces ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp/metrics ]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp/logs ]
